const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const {JSDOM}=require(process.env.QA_JSDOM_PATH||'jsdom');
function boot(){const d=new JSDOM(fs.readFileSync('docs/index.html','utf8'),{url:'https://example.test/namima/?secret=test#local',runScripts:'outside-only',pretendToBeVisual:true}),w=d.window;w.HTMLCanvasElement.prototype.getContext=function(t){return t==='webgl'?null:{fillRect(){}}};w.HTMLElement.prototype.getBoundingClientRect=()=>({width:180,height:150});w.HTMLElement.prototype.scrollIntoView=()=>{};w.scrollTo=()=>{};w.ResizeObserver=class{observe(){}};w.requestAnimationFrame=()=>1;w.matchMedia=()=>({matches:true});w.confirm=()=>true;w.localStorage.setItem('namima-progress-v1','[0,2]');w.localStorage.setItem('namima-inverse-v2','[0,5]');for(const f of ['model','session','app'])vm.runInContext(fs.readFileSync('docs/'+f+'.js','utf8'),d.getInternalVMContext());return w}
function change(w,i,v){const e=w.document.querySelector('#knob'+i);e.value=v;e.dispatchEvent(new w.Event('input'));e.dispatchEvent(new w.Event('change'))}
function solve(w){const r=w.eval('round()');r.level.controls.forEach((c,i)=>change(w,i,w.WaveModel.get(r.level.target,c.key)))}
function finish(w,solveAll=false){for(let n=0;n<5;n++){if(solveAll)solve(w);w.document.querySelector('#primary').click();w.document.querySelector('#primary').click()}}
test('Home starts with three difficulty choices and no active scores; legacy progress untouched',()=>{const w=boot(),d=w.document;a(!d.querySelector('#home').hidden);a(d.querySelector('#play').hidden);a.equal(d.querySelectorAll('[data-difficulty]').length,3);a.equal(w.localStorage.getItem('namima-progress-v1'),'[0,2]');a.equal(w.localStorage.getItem('namima-inverse-v2'),'[0,5]');w.close()});
for(const mode of ['easy','normal','hard'])test(`${mode}: five exact solutions through UI give 500, no auto judge, then results`,()=>{const w=boot(),d=w.document;w.eval(`start('${mode}',18)`);for(let n=0;n<5;n++){solve(w);a(!w.eval('judged'));a.equal(w.eval('round().score'),null);a.equal(d.querySelector('#judgment').textContent,'');d.querySelector('#primary').click();a(w.eval('judged'));a(d.querySelector('#judgment').textContent.includes('100.0%'));a.equal(d.querySelectorAll('.answer-marker').length,w.eval('round().level.controls.length'));d.querySelector('#primary').click()}a(!d.querySelector('#results').hidden);a.equal(d.querySelector('#totalScore').textContent,'500.0');a.equal(d.querySelectorAll('#roundScores li').length,5);w.close()});
test('Low initial results advance, retry/reset never inflate first score or expose target before judging',()=>{const w=boot(),d=w.document;w.eval("start('normal',12)");d.querySelector('#primary').click();const first=w.eval('round().score');a(first<100);a([...d.querySelectorAll('#controls input')].every(x=>x.disabled));d.querySelector('#reset').click();a.equal(d.querySelector('#judgment').textContent,'');a.equal(d.querySelectorAll('.answer-marker,.answer-value,.answer-source').length,0);solve(w);d.querySelector('#primary').click();a(d.querySelector('#judgment').textContent.includes('100.0%'));a.equal(w.eval('round().score'),first);d.querySelector('#reset').click();a.equal(w.eval('round().score'),first);a.equal(d.querySelector('#judgment').textContent,'');a.equal(w.eval('JSON.stringify(state)'),w.eval('JSON.stringify(round().level.initial)'));d.querySelector('#primary').click();d.querySelector('#primary').click();a.equal(w.eval('game.index'),1);a.equal(w.eval('round().score'),null);w.close()});
test('Undo, nudge, hints and palette progression are consistent',()=>{const w=boot(),d=w.document;w.eval("start('hard',15)");const before=w.eval('JSON.stringify(state)');d.querySelector('[data-step="0,1"]').click();a.notEqual(w.eval('JSON.stringify(state)'),before);d.querySelector('#undo').click();a.equal(w.eval('JSON.stringify(state)'),before);for(let i=0;i<3;i++)d.querySelector('#hint').click();a.equal(w.eval('round().hints'),3);a(d.querySelector('#hintText').textContent.includes('ひとつの解'));const c=w.eval('round().color.name');d.querySelector('#primary').click();d.querySelector('#primary').click();a.notEqual(w.eval('round().color.name'),c);a.equal(w.eval('round().hints'),0);a(d.querySelector('#hintText').hidden);w.close()});
test('No live evaluator calls, equal backing dimensions and labels',()=>{const w=boot(),d=w.document;w.eval("start('easy',2)");let count=0;const fn=w.WaveModel.evaluate;w.WaveModel.evaluate=(...xs)=>{count++;return fn(...xs)};solve(w);a.equal(count,0);a.equal(d.querySelector('#target').width,d.querySelector('#current').width);a.equal(d.querySelector('#target').height,d.querySelector('#current').height);for(const e of d.querySelectorAll('#controls input'))a(d.querySelector(`label[for="${e.id}"]`));d.querySelector('#primary').click();a.equal(count,1);a.equal(d.querySelectorAll('[id]').length,new Set([...d.querySelectorAll('[id]')].map(x=>x.id)).size);w.close()});
test('Native share contains actual difficulty/total and clean project URL; cancellation does not copy',async()=>{const w=boot(),d=w.document;w.eval("start('hard',9)");finish(w);let payload,copied=0;w.navigator.share=async x=>payload=x;w.navigator.clipboard={writeText:async()=>copied++};await w.eval('share()');a(payload.text.includes(w.NamimaSession.total(w.eval('game')).toFixed(1)+' / 500'));a(payload.text.includes('ハード'));a(payload.text.endsWith('https://example.test/namima/'));a(!payload.text.includes('secret'));a.equal(copied,0);w.navigator.share=async()=>{const e=Error();e.name='AbortError';throw e};await w.eval('share()');a.equal(copied,0);w.close()});
test('Clipboard and manual fallbacks work, no automatic sharing',async()=>{const w=boot(),d=w.document;let copy=null;w.navigator.clipboard={writeText:async x=>copy=x};w.eval("start('easy',2)");finish(w);a.equal(copy,null);await w.eval('share()');a(copy.includes('5問・初回判定'));w.navigator.clipboard={writeText:async()=>{throw Error('denied')}};await w.eval('share()');a(!d.querySelector('#copyFallback').hidden);a(d.querySelector('#shareText').value.includes('イージー'));w.close()});
test('Early results/share are impossible and new session clears old result',async()=>{const w=boot(),d=w.document;let n=0;w.navigator.share=async()=>n++;w.eval("start('easy',10);showResults()");a(d.querySelector('#results').hidden);await w.eval('share()');a.equal(n,0);finish(w);d.querySelector('#again').click();a.equal(w.eval('game.index'),0);a(w.eval('game.rounds.every(r=>r.score===null)'));a(d.querySelector('#results').hidden);a.equal(d.querySelector('#judgment').textContent,'');w.close()});
test('Native share failure falls back to clipboard and never changes score',async()=>{const w=boot();w.eval("start('normal',22)");finish(w);const before=w.eval('JSON.stringify(game.rounds.map(r=>r.score))');let text;w.navigator.share=async()=>{throw Error('unavailable')};w.navigator.clipboard={writeText:async x=>text=x};await w.eval('share()');a(text.includes('ノーマル'));a.equal(w.eval('JSON.stringify(game.rounds.map(r=>r.score))'),before);w.close()});
test('Requested explanations and retry button are absent across home, play, judge, reset and results',()=>{const w=boot(),d=w.document;const forbidden=['FIVE LITTLE WAVES','この模様、','どんな波でできている？','見本を見ながら、波を重ねる。','5つの風景を、あなたの目で復元しよう。','縞の間隔、曲がり方、明暗を見比べよう。準備ができたら','この点数をセットの記録にしました。','◆ は正解設定の一例です。','別の設定でも同じ模様になることがあります。点数にかかわらず次へ進めます。','◆ 解の一例：','つまみの◆と波源の◆が、正解設定の一例です。','もう一度試す','セットの点数には、この問題の最初の判定を使います。','正解の先にも、模様はつづく。'];function check(){for(const text of forbidden)a(!d.body.textContent.includes(text),text);for(const id of ['retry','instruction','scorePolicy'])a.equal(d.querySelector('#'+id),null);a.equal(d.querySelector('footer'),null);a.equal(d.querySelectorAll('.answer-value').length,0)}check();w.eval("start('easy',22)");check();d.querySelector('#primary').click();check();a(d.querySelector('#judgment').textContent.includes('一致率'));a.equal(d.querySelector('#judgment').children.length,2);for(const e of d.querySelectorAll('.answer-marker')){a.equal(e.textContent,'◆');a.equal(e.getAttribute('role'),'img');a(e.getAttribute('aria-label').includes('正解位置'));a(d.querySelector(`[aria-describedby="${e.id}"]`))}d.querySelector('#reset').click();check();finish(w);check();a(!d.querySelector('#results').hidden);a.equal(d.querySelectorAll('#roundScores li').length,5);w.close()});

test('Removed copy leaves no reserved containers or orphaned visibility selector',()=>{const css=fs.readFileSync('docs/style.css','utf8');a(css.includes('[hidden]{display:none!important}'));a(!css.includes('body:has(#play:not([hidden])) footer'));for(const selector of ['.instruction{','.answer-value{','.retry{','footer{'])a(!css.includes(selector));});

test('Changed UI assets have matching cache-busting release versions',()=>{const html=fs.readFileSync('docs/index.html','utf8');a(html.includes('href="style.css?v=5.2.1"'));a(html.includes('src="app.js?v=5.2.1"'));a(!html.includes('src="app.js"'));a(!html.includes('href="style.css"'));});


test('Home contains only three direct difficulty choices and restores game navigation',()=>{const w=boot(),d=w.document;const home=d.querySelector('#home');a.deepEqual([...home.querySelectorAll('button')].map(x=>x.textContent),['イージー','ノーマル','ハード']);a.equal(home.textContent,'イージーノーマルハード');a.equal(home.querySelectorAll('canvas,h1,h2,p,small,span').length,0);a(!d.querySelector('.topbar').hidden);for(const mode of ['easy','normal','hard']){d.querySelector(`[data-difficulty="${mode}"]`).click();a.equal(w.eval('game.mode'),mode);a.equal(w.eval('game.index'),0);a.equal(w.eval('game.rounds.length'),5);a(!d.querySelector('.topbar').hidden);d.querySelector('#leave').click();a(!home.hidden);a(!d.querySelector('.topbar').hidden)}w.close()});

test('Instructions remain available from the minimal home and open and close',()=>{const w=boot(),d=w.document,dialog=d.querySelector('#aboutDialog');dialog.showModal=()=>dialog.setAttribute('open','');dialog.close=()=>dialog.removeAttribute('open');a.equal(d.querySelector('#about').textContent,'遊び方');d.querySelector('#about').click();a(dialog.hasAttribute('open'));a(dialog.textContent.includes('準備ができたら'));d.querySelector('#closeAbout').click();a(!dialog.hasAttribute('open'));a(!d.querySelector('#home').hidden);w.close()});
