const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const {JSDOM}=require(process.env.QA_JSDOM_PATH||'jsdom');
function boot(){const d=new JSDOM(fs.readFileSync('docs/index.html','utf8'),{url:'https://example.test/namima/?secret=test#local',runScripts:'outside-only',pretendToBeVisual:true}),w=d.window;w.HTMLCanvasElement.prototype.getContext=function(t){return t==='webgl'?null:{fillRect(){}}};w.HTMLElement.prototype.getBoundingClientRect=()=>({width:180,height:150});w.HTMLElement.prototype.scrollIntoView=()=>{};w.scrollTo=()=>{};w.ResizeObserver=class{observe(){}};w.requestAnimationFrame=()=>1;w.matchMedia=()=>({matches:true});w.confirm=()=>true;w.localStorage.setItem('namima-progress-v1','[0,2]');w.localStorage.setItem('namima-inverse-v2','[0,5]');for(const f of ['model','session','app'])vm.runInContext(fs.readFileSync('docs/'+f+'.js','utf8'),d.getInternalVMContext());return w}
function change(w,i,v){const e=w.document.querySelector('#knob'+i);e.value=v;e.dispatchEvent(new w.Event('input'));e.dispatchEvent(new w.Event('change'))}
function solve(w){const r=w.eval('round()');r.level.controls.forEach((c,i)=>change(w,i,w.WaveModel.get(r.level.target,c.key)))}
function finish(w,solveAll=false){for(let n=0;n<5;n++){if(solveAll)solve(w);w.document.querySelector('#primary').click();w.document.querySelector('#primary').click()}}
test('Home starts with three difficulty choices and no active scores; legacy progress untouched',()=>{const w=boot(),d=w.document;a(!d.querySelector('#home').hidden);a(d.querySelector('#play').hidden);a.equal(d.querySelectorAll('[data-difficulty]').length,3);a.equal(w.localStorage.getItem('namima-progress-v1'),'[0,2]');a.equal(w.localStorage.getItem('namima-inverse-v2'),'[0,5]');w.close()});
for(const mode of ['easy','normal','hard'])test(`${mode}: five exact solutions through UI give 500, no auto judge, then results`,()=>{const w=boot(),d=w.document;w.eval(`start('${mode}',18)`);for(let n=0;n<5;n++){solve(w);a(!w.eval('judged'));a.equal(w.eval('round().score'),null);a.equal(d.querySelector('#judgment').textContent,'');d.querySelector('#primary').click();a(w.eval('judged'));a(d.querySelector('#judgment').textContent.includes('100.0%'));a.equal(d.querySelectorAll('.answer-marker').length,w.eval('round().level.controls.length'));d.querySelector('#primary').click()}a(!d.querySelector('#results').hidden);a.equal(d.querySelector('#totalScore').textContent,'500.0');a.equal(d.querySelectorAll('#roundScores li').length,5);w.close()});
test('Low initial results advance, retry/reset never inflate first score or expose target before judging',()=>{const w=boot(),d=w.document;w.eval("start('normal',12)");d.querySelector('#primary').click();const first=w.eval('round().score');a(first<100);a([...d.querySelectorAll('#controls input')].every(x=>x.disabled));d.querySelector('#retry').click();a.equal(d.querySelector('#judgment').textContent,'');a.equal(d.querySelectorAll('.answer-marker,.answer-value,.answer-source').length,0);solve(w);d.querySelector('#primary').click();a(d.querySelector('#judgment').textContent.includes('100.0%'));a.equal(w.eval('round().score'),first);d.querySelector('#reset').click();a.equal(w.eval('round().score'),first);a.equal(d.querySelector('#judgment').textContent,'');a.equal(w.eval('JSON.stringify(state)'),w.eval('JSON.stringify(round().level.initial)'));d.querySelector('#primary').click();d.querySelector('#primary').click();a.equal(w.eval('game.index'),1);a.equal(w.eval('round().score'),null);w.close()});
test('Undo, nudge, hints and palette progression are consistent',()=>{const w=boot(),d=w.document;w.eval("start('hard',15)");const before=w.eval('JSON.stringify(state)');d.querySelector('[data-step="0,1"]').click();a.notEqual(w.eval('JSON.stringify(state)'),before);d.querySelector('#undo').click();a.equal(w.eval('JSON.stringify(state)'),before);for(let i=0;i<3;i++)d.querySelector('#hint').click();a.equal(w.eval('round().hints'),3);a(d.querySelector('#hintText').textContent.includes('ひとつの解'));const c=w.eval('round().color.name');d.querySelector('#primary').click();d.querySelector('#primary').click();a.notEqual(w.eval('round().color.name'),c);a.equal(w.eval('round().hints'),0);a(d.querySelector('#hintText').hidden);w.close()});
test('No live evaluator calls, equal backing dimensions and labels',()=>{const w=boot(),d=w.document;w.eval("start('easy',2)");let count=0;const fn=w.WaveModel.evaluate;w.WaveModel.evaluate=(...xs)=>{count++;return fn(...xs)};solve(w);a.equal(count,0);a.equal(d.querySelector('#target').width,d.querySelector('#current').width);a.equal(d.querySelector('#target').height,d.querySelector('#current').height);for(const e of d.querySelectorAll('#controls input'))a(d.querySelector(`label[for="${e.id}"]`));d.querySelector('#primary').click();a.equal(count,1);a.equal(d.querySelectorAll('[id]').length,new Set([...d.querySelectorAll('[id]')].map(x=>x.id)).size);w.close()});
test('Native share contains actual difficulty/total and clean project URL; cancellation does not copy',async()=>{const w=boot(),d=w.document;w.eval("start('hard',9)");finish(w);let payload,copied=0;w.navigator.share=async x=>payload=x;w.navigator.clipboard={writeText:async()=>copied++};await w.eval('share()');a(payload.text.includes(w.NamimaSession.total(w.eval('game')).toFixed(1)+' / 500'));a(payload.text.includes('ハード'));a(payload.text.endsWith('https://example.test/namima/'));a(!payload.text.includes('secret'));a.equal(copied,0);w.navigator.share=async()=>{const e=Error();e.name='AbortError';throw e};await w.eval('share()');a.equal(copied,0);w.close()});
test('Clipboard and manual fallbacks work, no automatic sharing',async()=>{const w=boot(),d=w.document;let copy=null;w.navigator.clipboard={writeText:async x=>copy=x};w.eval("start('easy',2)");finish(w);a.equal(copy,null);await w.eval('share()');a(copy.includes('5問・初回判定'));w.navigator.clipboard={writeText:async()=>{throw Error('denied')}};await w.eval('share()');a(!d.querySelector('#copyFallback').hidden);a(d.querySelector('#shareText').value.includes('イージー'));w.close()});
test('Early results/share are impossible and new session clears old result',async()=>{const w=boot(),d=w.document;let n=0;w.navigator.share=async()=>n++;w.eval("start('easy',10);showResults()");a(d.querySelector('#results').hidden);await w.eval('share()');a.equal(n,0);finish(w);d.querySelector('#again').click();a.equal(w.eval('game.index'),0);a(w.eval('game.rounds.every(r=>r.score===null)'));a(d.querySelector('#results').hidden);a.equal(d.querySelector('#judgment').textContent,'');w.close()});
test('Native share failure falls back to clipboard and never changes score',async()=>{const w=boot();w.eval("start('normal',22)");finish(w);const before=w.eval('JSON.stringify(game.rounds.map(r=>r.score))');let text;w.navigator.share=async()=>{throw Error('unavailable')};w.navigator.clipboard={writeText:async x=>text=x};await w.eval('share()');a(text.includes('ノーマル'));a.equal(w.eval('JSON.stringify(game.rounds.map(r=>r.score))'),before);w.close()});
test('Reset before first judgment uses first-attempt copy; practice hides numeric score during adjustment',()=>{const w=boot(),d=w.document;w.eval("start('easy',22)");d.querySelector('#reset').click();a(!d.querySelector('#instruction').textContent.includes('最初の判定から変わりません'));d.querySelector('#primary').click();d.querySelector('#retry').click();a(!d.querySelector('.control-panel').textContent.includes('%'));a(!d.querySelector('#scorePolicy').textContent.match(/\d/));w.close()});
